---
# Ansible rpm build automation for Glare client
# Usage: "ansible-playbook -i <TARGET_HOST_NAME>, glareclient_rpm_build_automation.yaml --extra-vars='ansible_become_pass=<REMOTE_PASSWORD> remote_user=<REMOTE_USER>''
# Example: ansible-playbook -i 192.168.56.101, glareclient_rpm_build_automation.yaml --extra-vars='ansible_become_pass=qwerty remote_user=mfedosin'
# Output: built packages in rpms/ folders
# CentOS 7 is required for target host
- name: Ansible rpmbuild for Glare
  hosts: all
  tasks:
    - name: Create build folders
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ ansible_user_dir }}/rpmbuild"
        - "{{ ansible_user_dir }}/rpmbuild/SPECS"
        - "{{ ansible_user_dir }}/rpmbuild/SOURCES"
    - name: Download glare tarball and systemd spec
      get_url:
        url: "http://tarballs.openstack.org/python-glareclient/python-glareclient-master.tar.gz"
        dest: "{{ ansible_user_dir }}/rpmbuild/SOURCES"
    - name: Download glareclient rpm spec
      get_url:
        url: "https://raw.githubusercontent.com/Fedosin/glare-rpm/master/python-glareclient.spec"
        dest: "{{ ansible_user_dir }}/rpmbuild/SPECS"
        validate_certs: False
    - name: Get current version
      shell: "tar tf '{{ ansible_user_dir }}/rpmbuild/SOURCES/python-glareclient-master.tar.gz' | head -1 | awk '{ print substr( $0, 20, length($0)-20 ) }'"
      register: command_output
    - set_fact:
        glareclient_version: "{{ command_output.stdout }}"
    - name: Rename tar file
      command: mv '{{ ansible_user_dir }}/rpmbuild/SOURCES/python-glareclient-master.tar.gz' '{{ ansible_user_dir }}/rpmbuild/SOURCES/python-glareclient-{{ glareclient_version }}.tar.gz'
    - name: Set version for the spec
      lineinfile:
        dest: "{{ ansible_user_dir }}/rpmbuild/SPECS/python-glareclient.spec"
        regexp: 'Version:[ \t]+XXX$'
        line: 'Version:          {{ glareclient_version }}'
    - name: Enable OpenStack Ocata repository
      yum:
        name: centos-release-openstack-ocata
        state: present
      become: yes
    - name: Get list of build requirements
      shell: "grep BuildRequires {{ ansible_user_dir }}/rpmbuild/SPECS/openstack-glare.spec | cut -c 19- | cut -d ' ' -f 1"
      register: command_output
    - set_fact:
        build_requirments: "{{ command_output.stdout_lines }}"
    - name: Install build requirements
      yum:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        "{{ build_requirments }}"
    - name: Build glareclient packages
      shell: "rpmbuild -ba {{ ansible_user_dir }}/rpmbuild/SPECS/python-glareclient.spec"
    - name: Get list of built files
      shell: "ls {{ ansible_user_dir }}/rpmbuild/RPMS/noarch | grep {{ glareclient_version }}"
      register: command_output
    - set_fact:
        built_packages: "{{ command_output.stdout_lines }}"
    - name: Fetch built files
      fetch:
        src: "{{ ansible_user_dir }}/rpmbuild/RPMS/noarch/{{ item }}"
        dest: rpms/
        flat: yes
      with_items:
        "{{ built_packages }}"
